config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get "about",to: 'pages#about'
  resources :articles
  get "signup",to: "users#new"
  resources :users, except: [:new]

  get "login",to: "sessions#new"
  post "login",to: "sessions#create"
  get "logout",to: "sessions#destroy"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article<ApplicationRecord
    belongs_to :user
    validates :title ,presence: true,length: {minimum: 3,maximum: 4000}
    validates :description,presence: true,length: {minimum: 3,maximum: 4000}
end

app/models/category.rb
class Category<ApplicationRecord
end

app/models/user.rb
class User<ApplicationRecord
    has_many :articles ,dependent: :destroy 
    before_save {self.email=email.downcase}
    VALID_EMAIL=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username,presence: true, length: {minimum: 2,maximum: 250},
            uniqueness: {case_sensitive: false}
    validates :email,presence: true,length: {maximum: 250},
            uniqueness: {case_sensitive: false},format: {with: VALID_EMAIL}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :curent_user,:logged_in?
    def curent_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    def logged_in?
        !!curent_user
    end
    def require_user
        if !logged_in?
            flash[:alert]="You must be logged in to perform this operation"
            redirect_to login_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController<ApplicationController
    before_action :set_article,only: [:show,:edit,:update,:destroy]
    before_action :require_user,except: [:show,:index]
    before_action :requre_same_user,only: [:edit,:destroy,:update]
    def show
    end
    def index
        @articles=Article.paginate(page: params[:page], per_page: 3)
    end
    def new
        @article=Article.new
    end
    def create
        @article=Article.new(article_params)
        @article.user_id=curent_user.id
        if @article.save
            #redirect_to article_path(@article.id)
            flash[:notice]="Article was created successfully"
            redirect_to @article
        else
            render "new"
        end
    end
    def edit
    end
    def update
        if @article.update(article_params)
            flash[:notice]="Article was updated successfully"
            redirect_to @article
        else
            render "edit"
        end

    end
    def destroy
        @article.destroy
        flash[:notice]="Article is deleted successfully"
        redirect_to articles_path
    end
    private
    def set_article
        @article=Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title,:description)
    end
    def requre_same_user
        if curent_user != @article.user && !curent_user.admin?
            flash[:alert]="you only edit or delete your own articles"
            redirect_to article_path(@article.id)
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController
    def new
    end
    def create
        user=User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]=user.id
            flash[notice]="Logged in successfully"
            redirect_to user_path(user.id)
        else
            flash.now[:alert]="Ther was something wrong with your credentials"
            render "new"
        end
    end
    def destroy
        session[:user_id]=nil
        flash[:notice]="You are Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController<ApplicationController
    before_action :set_user,only: [:show,:edit,:update,:destroy]
    before_action :require_user,only: [:edit,:update]
    before_action :requre_same_user,only: [:edit,:update,:destroy]
    def new
        @user=User.new
    end
    def create
        @user=User.new(user_params)
        if @user.save
            session[:user_id]=@user.id
            flash[:notice]="Welcome #{@user.username} You have successfully signed in..!"
            redirect_to articles_path
        else
            render "new"
        end
    end
    def edit
    end
    def update
       
        if @user.update(user_params)
            flash[:notice]="Your Account details has been successfully updated..!"
            redirect_to user_path(@user.id)
        else
            render "edit"
        end
    end
    def show
        @articles=@user.articles.paginate(page: params[:page], per_page: 2)
    end
    def index
        @users=User.paginate(page: params[:page], per_page: 3)
    end
    def destroy
        @user.destroy
        session[:user_id]=nil if @user==curent_user
        flash[:notice]="account and associated articles are destroyed"
        redirect_to root_path
    end
    private
    def user_params
        params.require(:user).permit(:username,:email,:password)
    end
    def set_user
        @user=User.find(params[:id])
    end
    def requre_same_user
        if curent_user != @user && !curent_user.admin?
            flash[:alert]="you only edit or delete your own articles"
            redirect_to user_path(@user.id)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravator_for(user,options={size: 80})
        email_address=user.email.downcase
        hash=Digest::MD5.hexdigest(email_address)
        size=options[:size]
        gravatar_url="https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(gravatar_url,alt: user.username,class: "rounded mx-auto d-block shadow-lg mt-3")
    end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article|%>
        <div class="row justify-content-center">
            <div class="col-8 mt-5">
                <div class="card text-center shadow-lg">
                    <div class="card-header font-italic">
                    <% if article.user%>
                        <%= link_to article.user.username ,user_path(article.user.id)%>
                    <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to article.title,article_path(article),class: "text-success title"%></h5>
                        <p class="card-text"><%= truncate(article.description,length: 400)%></p>
                        <%= link_to "View",article_path(article),class: "btn btn-outline-success" %>
                        <% if logged_in? && (article.user==curent_user || curent_user.admin?) %>
                            <%= link_to "Edit" , edit_article_path(article), class: "btn btn-outline-success" %>
                            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger",method: :delete, data: {confirm: "Are you sure?"} %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                        created <%= time_ago_in_words(article.created_at)%> ago
                        updated <%= time_ago_in_words(article.updated_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
</div>

app/views/articles/_form.html.erb
<div class="container mt-4">
    <div class="container row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors",obj: @article %>
            <%= form_with(model: @article, class: "shadow-lg p-3 mb-3 bg-info rounded",local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :title,class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :title ,class: "form-control shadow rounded",placeholder: "Title of the article"%>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :description,class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_area :description ,rows: 10,class: "form-control shadow rounded",placeholder: "Description of the article"%>
                    </div>
                </div>
                <div class="form-group text-center">
                    <%=f.submit class: "btn btn-outline-light btn-lg"%>
                </div>
            <%end%>
        </div>
        <%= link_to "[Return]",articles_path,class: "text-center text-info"%>
    </div>
</div>

app/views/articles/edit.html.erb
<div id="page-content">
    <h1 class="text-center mt-5">Edit article</h1>
    <%= render "form" %>
</div>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">Listing all the Articles</h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render "article" %>
</br>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
</br>

app/views/articles/new.html.erb
<h1 class="text-center mt-5">create a new article</h1>
<%= render "form" %>

app/views/articles/show.html.erb
<h2 class="text-center mt-4"><%= @article.title%></h2>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8 mt-3">
            <div class="card text-center shadow-lg">
                <div class="card-header font-italic">
                    <%= @article.user.username if @article.user%>
                    <%= link_to gravator_for(@article.user,options={size: 100}) ,user_path(@article.user.id)%>
                </div>
                <div class="card-body">
                    <div class="card-text text-left"><%= simple_format(@article.description) %></div>
                    <% if logged_in? && (@article.user==curent_user || curent_user.admin?)%>
                        <%= link_to "Edit" , edit_article_path(@article), class: "btn btn-outline-success"%>
                        <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger",method: :DELETE, data: {confirm: "Are you sure?"} %>
                    <% end %>
                </div>
                <div class="card-footer text-muted">
                    <small>
                    created <%= time_ago_in_words(@article.created_at)%> ago
                    updated <%= time_ago_in_words(@article.updated_at)%> ago
                    </small>
                </div>
            </div>
        </div>
    </div>
</div>
</br>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white">
    <div class="container text-center">
        <small>Copyright &copy; srinu chintha</small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container mt-2">
    <% flash.each do |key,mesg| %>
        <div class="alert alert-<%= key == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
            <%= mesg%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <%end%>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "ALPHA BLOG",root_path,class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto ">
      <li class="nav-item">
        <%= link_to "Bloogers",users_path,class: "nav-link text-light"%>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
          <%= link_to "New Article",new_article_path,class: "dropdown-item"%>
          <% end %>
          <%= link_to "View Article",articles_path,class: "dropdown-item"%>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
              <%= "(admin)" if curent_user.admin? %> Profile [<%= curent_user.username %>]
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "View Profile",user_path(curent_user.id),class: "dropdown-item"%>
                <%= link_to "Edit your profile",edit_user_path(curent_user.id),class: "dropdown-item"%>
                <%= link_to "Delete your profile",user_path(curent_user.id),method: :delete,data: {confirm: "are you sure?"},class: "dropdown-item text-danger"%>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        <li class="nav-item">
          <%= link_to "logout",logout_path,class: "nav-link text-light", method: :delete %>
        </li>
        <li class="nav-item">
          <%= link_to curent_user.username,user_path(curent_user.id),class: "nav-link text-light"%>
        </li>
      <% else %>  
        <li class="nav-item">
          <%= link_to "login",login_path,class: "nav-link text-light"%>
        </li>
        <li class="nav-item">
        <%= link_to "SignUp",signup_path,class: "nav-link text-light"%>
      </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">

    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="d-flex flex-column">
    <%= render "layouts/navigation"%>  
    <div id="page-content">
      <%= render "layouts/messages"%>
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
<%= link_to "Articles",articles_path%> |
<%= link_to "home",root_path%>

app/views/pages/home.html.erb
<div class="container mt-5" id="page-content">
    <div class="jumbotron text-center jubotron-background p-5 d-flex flex-column justify-content-center text-light">
        <h1 class="display-4">ALPHA BLOG</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <div>
            <%= link_to "SignUp",signup_path,class: "btn btn-success btn-lg"%>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase%> to save</h4>
        <ul>
            <% obj.errors.full_messages.each do |mesg| %>
                <li><%= mesg %></li>
            <% end %>
        </ul>
    
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
<% end %>


        

app/views/users/_form.html.erb
<div class="container mt-4">
    <div class="container row justify-content-center">
        <div class="col-10">
            <%= render "shared/errors",obj: @user %>
            <%= form_with(model: @user, class: "shadow-lg p-3 mb-3 bg-info rounded",local: true) do |f| %>
                <div class="form-group row">
                    <%= f.label :username,class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.text_field :username ,class: "form-control shadow rounded",placeholder: "Enter a username"%>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :email,class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.email_field :email ,rows: 10,class: "form-control shadow rounded",placeholder: "Enter your email"%>
                    </div>
                </div>
                <div class="form-group row">
                    <%= f.label :password,class: "col-2 col-form-label text-light" %>
                    <div class="col-10">
                        <%= f.password_field :password ,rows: 10,class: "form-control shadow rounded",placeholder: "Chose a password"%>
                    </div>
                </div>
                <div class="form-group text-center">
                    <%=f.submit(@user.new_record? ? "SignUp" : "Update Accout",class: "btn btn-outline-light btn-lg")%>
                </div>
            <%end%>
        </div>
        <%= link_to "[Return]",articles_path,class: "text-center text-info"%>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-5">Edit your profile</h1>
<%= render "form" %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpha bloggers</h1>
<div class="flickr_pagination">
    <%= will_paginate @users, :container => false %>
</div>
<div class="container">
    <% @users.each do |user|%>
        <div class="row justify-content-center">
            <div class="col-8 mt-5">
                <div class="card text-center shadow-lg">
                    <div class="card-header font-italic">
                        <%= link_to user.username,user_path(user) %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                        <%= link_to gravator_for(user,size: 200),user_path(user),class: "text-success title"%>
                        </h5>
                        <p class="card-text"><%= pluralize(user.articles.count,"article")%></p>
                        <%= link_to "View profile",user_path(user),class: "btn btn-outline-success" %>
                        <% if logged_in? %> 
                            <% if user==curent_user %>
                                <%= link_to "Edit profile" , edit_user_path(user), class: "btn btn-outline-success"%>
                            <% end %>    
                            <% if curent_user.admin? %>
                                <%= link_to "Delete Profile" , user_path(user),method: :delete,data: {confirm: "are you sure?"}, class: "btn btn-outline-danger"%>
                            <% end %>
                        <% end %>
                    </div>
                    <div class="card-footer text-muted">
                        <small>
                        joined <%= time_ago_in_words(user.created_at)%> ago
                        </small>
                    </div>
                </div>
            </div>
        </div>
    <%end%>
</div>
<div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-5">SignUp for ALPHABLOG</h1>
<%= render "form" %>

app/views/users/show.html.erb
<h1 class="text-center mt-5"><%= @user.username %></h1>
<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= gravator_for(@user,size: 300)%>
<h3 class="text-center mt-2">Articles</h3>
<% if logged_in? && @user==curent_user%>
<div class="text-center mt-3">
    <%= link_to "Edit your profile",edit_user_path(@user),class: "btn btn-outline-info" %>
</div>
<% end %>
<%= render "articles/article" %>

<div class="flickr_pagination mt-4 mb-4">
    <%= will_paginate @articles, :container => false %>
</div>